[0m03:15:40  Running with dbt=1.9.8
[0m03:15:41  Registered adapter: snowflake=1.9.1
[0m03:15:42  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m03:15:42  
[0m03:15:42  Concurrency: 4 threads (target='embucket')
[0m03:15:42  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f307c3df7d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=b30a8981-3994-4d47-8fdc-1a70167ddc26&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f308425f830>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=e4ca5ab1-bbd5-4026-aa09-5ed132511b1e&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f307c35a750>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=17b4e486-206c-4475-a8d6-ff55953b492d&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f307ca5e450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=9bf5f758-1957-45cb-b2d7-504de09446f6&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f307ca5e570>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=261a8027-de7a-4eaf-ba87-88bf932a7b4e&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f30988e69c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=42019b76-39ca-480f-9f87-9c52083b9799&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m03:15:43  
[0m03:15:43  Finished running  in 0 hours 0 minutes and 1.47 seconds (1.47s).
[0m03:15:43  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
