[0m03:12:33  Running with dbt=1.9.8
[0m03:12:34  Registered adapter: snowflake=1.9.1
[0m03:12:35  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m03:12:35  
[0m03:12:35  Concurrency: 4 threads (target='embucket')
[0m03:12:35  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f6d88d93f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=56525d98-ca5d-4801-af4f-4d4bee3215dd&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f6d88d900b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=4f34cf87-0f11-4e60-bc4f-f2a03c75594a&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f6d9945f9e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=fa02b3e8-fc75-4599-bafa-d41184a7eeda&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f6d88d716d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=d9d1012d-f534-4421-8992-d071c2efd957&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f6d88d70500>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=672db1a3-6362-4fd3-b291-1bfdf1bbff11&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f6d88d70c50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=883c3b30-eaf6-46d1-9f13-541a23fe6132&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m03:12:36  
[0m03:12:36  Finished running  in 0 hours 0 minutes and 1.44 seconds (1.44s).
[0m03:12:36  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
