[0m03:20:30  Running with dbt=1.9.8
[0m03:20:31  Registered adapter: snowflake=1.9.1
[0m03:20:32  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m03:20:32  
[0m03:20:32  Concurrency: 4 threads (target='embucket')
[0m03:20:32  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f7014dd6d80>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=c5a6a10e-36ba-4427-a8e5-93e00b024628&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f701406f890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=c119b9d5-a351-4a16-842a-182ec1c9e722&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f700cf10fb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=9bcc4a7a-e58c-45a5-a514-c22acc36898e&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f7014dd4b30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=24b269e0-19db-46f8-a4fa-734e932aeaf7&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f700cf112b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=af358c9c-3a73-4141-9e75-120f92f586a2&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f702835c560>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=cf85fcbb-a9e1-4949-8d2f-d8de98786208&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m03:20:33  
[0m03:20:33  Finished running  in 0 hours 0 minutes and 1.46 seconds (1.46s).
[0m03:20:33  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
