[0m03:17:54  Running with dbt=1.9.8
[0m03:17:55  Registered adapter: snowflake=1.9.1
[0m03:17:56  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m03:17:56  
[0m03:17:56  Concurrency: 4 threads (target='embucket')
[0m03:17:56  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7fcb51495940>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=353bc534-61f4-4470-b999-c744b2a6c9e8&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7fcb4077ea50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=5dba78b4-d167-411a-b507-47375c497fbe&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7fcb4077f1d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=79e09d05-3ed5-4e70-b1e1-c24baf697a0e&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7fcb4062b080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=7c060912-f587-4c9d-8dd4-2c67fc28eb3e&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7fcb514945f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=b97c8c59-d26b-454f-b06e-b1ddf2331a30&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7fcb51494b30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=2b167745-4c7a-424d-8c0d-1fdbf382e3a5&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m03:17:57  
[0m03:17:57  Finished running  in 0 hours 0 minutes and 1.46 seconds (1.46s).
[0m03:17:57  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
