[0m03:12:59  Running with dbt=1.9.8
[0m03:13:00  Registered adapter: snowflake=1.9.1
[0m03:13:01  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m03:13:01  
[0m03:13:01  Concurrency: 4 threads (target='embucket')
[0m03:13:01  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f8212f32f00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=be14f54f-f3a8-488e-a714-a177b752668f&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f8212f32690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=91f299d3-f9ad-453c-bcc5-c13c647be38e&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f8210894110>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=b3c5144d-278d-45e7-bb9f-fccc4b138b72&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f821087f590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=04ea8039-296c-40fa-93bd-e8f250d13ef5&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f821087e930>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=22de332c-3b91-49a4-a3a4-3b0874ffbe62&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f821aebd4c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=22a778bd-b70d-412e-9542-6d1a0b67b874&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m03:13:02  
[0m03:13:02  Finished running  in 0 hours 0 minutes and 1.46 seconds (1.46s).
[0m03:13:02  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
