[0m04:04:22  Running with dbt=1.9.8
[0m04:04:23  Registered adapter: snowflake=1.9.1
[0m04:04:24  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m04:04:24  
[0m04:04:24  Concurrency: 4 threads (target='embucket')
[0m04:04:24  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f83647efb00>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=167991af-4c9a-4970-8391-be85986970ce&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f83647ee5a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=ab299dc6-f683-4b07-9150-5d12efca4419&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f8364d97080>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=a5580d79-9972-47fe-be99-f6396412dc9f&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f8354e1c5c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=e4125285-ca7f-4337-81a5-9cb38e9ce644&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f8354fea900>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=a0bd374a-162b-44ca-ba26-7915a0ebfc89&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f8368988e60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=cd8fbb1f-fafd-4d44-826f-e9bc39f801e2&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m04:04:25  
[0m04:04:25  Finished running  in 0 hours 0 minutes and 1.46 seconds (1.46s).
[0m04:04:25  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
