[0m04:04:42  Running with dbt=1.9.8
[0m04:04:43  Registered adapter: snowflake=1.9.1
[0m04:04:44  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m04:04:44  
[0m04:04:44  Concurrency: 4 threads (target='embucket')
[0m04:04:44  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f142057b860>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=0c85c432-7fdf-46fa-b011-b6ef6acac350&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f1420424d40>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=30e34c2f-1630-4f94-945f-8f43a5580ad5&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f1420426330>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=be4fa5f3-d80c-46fb-9abb-d680e2af2ec6&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f14204c51f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=426aed7a-a6ef-4364-a464-f174d5bce734&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f14204255e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=0e775730-1a7c-4ae0-925b-7783025824e4&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f1420425070>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=ec476da9-b712-4eb4-837c-9e568cc4baac&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m04:04:45  
[0m04:04:45  Finished running  in 0 hours 0 minutes and 1.46 seconds (1.46s).
[0m04:04:45  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
