[0m04:04:31  Running with dbt=1.9.8
[0m04:04:32  Registered adapter: snowflake=1.9.1
[0m04:04:32  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m04:04:32  
[0m04:04:32  Concurrency: 4 threads (target='embucket')
[0m04:04:32  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f1664a923c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=91cf409f-e67d-4e05-a7c9-d0824424fed4&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f166182b830>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=b06a191e-e945-4198-9ca1-9244b0f268c6&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f1650928800>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=418fe88a-3bf4-4a78-b3d6-640cd50bb091&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f16618297c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=261dab86-b4c1-4e7b-b41f-6b371da67c15&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f166187bef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=a5b3474e-c76d-45e3-a45c-c87fd16cf12a&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f165092bf50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=404795d3-554e-45d9-9e5b-ef6bb93d9950&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m04:04:34  
[0m04:04:34  Finished running  in 0 hours 0 minutes and 1.46 seconds (1.46s).
[0m04:04:34  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
