[0m04:04:08  Running with dbt=1.9.8
[0m04:04:09  Registered adapter: snowflake=1.9.1
[0m04:04:10  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m04:04:10  
[0m04:04:10  Concurrency: 4 threads (target='embucket')
[0m04:04:10  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f2450930050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=7f213fa7-097d-4133-9b3e-6d5129463c28&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f245878ea20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=64f3423a-4f3d-4c3e-a4ac-bf4668adbf16&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f2450931d60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=1a6f2512-5812-4eb3-ad52-5647ea512d0f&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f2450931df0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=41a1e328-d2d4-4701-afc2-4454ed7b3d5a&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f2450932990>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=a71bef49-01cc-421f-9796-6b1e99086aac&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f24509302c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=d4fe9abd-c93b-42a1-ada9-9e5af8f7507d&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m04:04:11  
[0m04:04:11  Finished running  in 0 hours 0 minutes and 1.48 seconds (1.48s).
[0m04:04:11  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
