[0m04:03:53  Running with dbt=1.9.8
[0m04:03:54  Registered adapter: snowflake=1.9.1
[0m04:03:55  Found 29 models, 120 data tests, 3 seeds, 2 operations, 8 sources, 768 macros
[0m04:03:55  
[0m04:03:55  Concurrency: 4 threads (target='embucket')
[0m04:03:55  
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f0f549db6e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=f80c814d-6701-40f1-bcb8-e6079a58f3c8&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f0f549d8620>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=0340006a-f892-4f3f-8f12-fd5e44682e76&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f0f549c0b60>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=97bbebb0-3f03-44d0-9de0-f645124668cb&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f0f5c0e0890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=62947c21-adc1-4a96-bdf5-038c83e816a6&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f0f5c0e1a30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=48473b27-fb41-4d11-ba59-2bcba3d5d038&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
WARNING:snowflake.connector.vendored.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x7f0f549c3800>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/v1/login-request?request_id=98956d30-b4fb-4917-9b16-4c9a2e7c1253&databaseName=EMBUCKET&schemaName=public&warehouse=COMPUTE_WH&roleName=SYSADMIN
[0m04:03:56  
[0m04:03:56  Finished running  in 0 hours 0 minutes and 1.47 seconds (1.47s).
[0m04:03:56  Encountered an error:
Runtime Error
  Database error while listing schemas in database "EMBUCKET"
  Database Error
    250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
